version: "3.9"
services:
  database:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=crxtest
    ports:
      - 5432:5432
    healthcheck:
      test: psql -U postgres -q -d postgres -c "SELECT 'ready';"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

volumes:
  db-data:
